# Generated by Django 6.0.3 on 2026-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_tokenusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='references/'),
        ),
    ]
