"""Export answers to various formats"""
import os
import tempfile
from django.conf import settings


def export_to_docx(project):
    """Export project Q&A to a formatted Word document"""
    import docx
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    
    doc = docx.Document()
    
    # Document properties
    doc.core_properties.title = project.name
    doc.core_properties.author = project.user.get_full_name() or project.user.username
    
    # Title
    title = doc.add_heading(project.name, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"Generated by DocuRAG | {project.updated_at.strftime('%B %d, %Y')}")
    run.font.color.rgb = RGBColor(100, 100, 100)
    run.font.size = Pt(10)
    
    doc.add_paragraph()
    
    # Summary stats
    questions = project.questions.select_related('answer').all()
    answered = questions.filter(status__in=['answered', 'reviewed']).count()
    
    stats_para = doc.add_paragraph()
    stats_para.add_run(f"Total Questions: {project.total_questions}  |  "
                       f"Answered: {answered}  |  "
                       f"Avg. Confidence: {round(project.confidence_score * 100)}%")
    stats_para.runs[0].font.size = Pt(10)
    stats_para.runs[0].font.color.rgb = RGBColor(80, 80, 80)
    
    doc.add_paragraph()
    
    # Group by category
    categories = {}
    for q in questions:
        cat = q.category or 'General'
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(q)
    
    for cat_name, cat_questions in categories.items():
        # Category header
        doc.add_heading(cat_name, level=1)
        
        for q in cat_questions:
            # Question
            q_para = doc.add_paragraph()
            q_run = q_para.add_run(f"Q{q.order}. {q.text}")
            q_run.bold = True
            q_run.font.size = Pt(11)
            
            # Answer
            if hasattr(q, 'answer'):
                answer_text = q.answer.final_answer
                a_para = doc.add_paragraph()
                a_para.add_run(answer_text)
                a_para.paragraph_format.left_indent = Inches(0.3)
                
                # Citations
                if q.answer.citations:
                    cit_para = doc.add_paragraph()
                    cit_para.paragraph_format.left_indent = Inches(0.3)
                    cit_run = cit_para.add_run("Sources: ")
                    cit_run.bold = True
                    cit_run.font.size = Pt(9)
                    cit_run.font.color.rgb = RGBColor(100, 100, 200)
                    
                    sources = []
                    for cit in q.answer.citations:
                        page = f" (p.{cit['page']})" if cit.get('page') else ""
                        sources.append(f"{cit['document']}{page}")
                    
                    src_run = cit_para.add_run('; '.join(sources))
                    src_run.font.size = Pt(9)
                    src_run.font.color.rgb = RGBColor(100, 100, 200)
            else:
                na_para = doc.add_paragraph()
                na_para.add_run("[ Not yet answered ]")
                na_para.runs[0].font.color.rgb = RGBColor(150, 150, 150)
            
            doc.add_paragraph()  # spacing
    
    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.docx')
    doc.save(tmp.name)
    return tmp.name


def export_to_json(project):
    """Export as structured JSON"""
    questions = project.questions.select_related('answer').all()
    
    data = {
        'project': project.name,
        'exported_at': project.updated_at.isoformat(),
        'total_questions': project.total_questions,
        'confidence_score': project.confidence_score,
        'questions': []
    }
    
    for q in questions:
        q_data = {
            'order': q.order,
            'question': q.text,
            'category': q.category,
            'status': q.status,
        }
        if hasattr(q, 'answer'):
            q_data['answer'] = q.answer.final_answer
            q_data['citations'] = q.answer.citations
            q_data['confidence'] = q.answer.confidence_score
            q_data['is_edited'] = q.answer.is_edited
        data['questions'].append(q_data)
    
    return data
